### ISSUE TITLE
arrays with elements <4 bytes cause MultiRoaringBitmap.jaccard_dist() seg fault

### ISSUE THREAD

**Issue by daveuu** [andreasvc/roaringbitmap#10]
```
from roaringbitmap import RoaringBitmap
from roaringbitmap import MultiRoaringBitmap
from array import array
a = RoaringBitmap(array('L',range(1,4)))
b = RoaringBitmap(array('L',range(3,6)))
c = RoaringBitmap(array('L',range(5,8)))
mrb = MultiRoaringBitmap([a,b,c])
# True
array('d', [0.8, 1.0]) == mrb.jaccard_dist(array('L',[1,1]),array('L',[2,3]))
array('d', [0.8, 1.0]) == mrb.jaccard_dist(array('Q',[1,1]),array('Q',[2,3]))
# these cause seg fault
d = mrb.jaccard_dist(array('H',[1,1]),array('H',[2,3]))
d = mrb.jaccard_dist(array('h',[1,1]),array('h',[2,3]))
d = mrb.jaccard_dist(array('I',[1,1]),array('I',[2,3]))
d = mrb.jaccard_dist(array('i',[1,1]),array('i',[2,3]))
```

**Comment by andreasvc** [comment]
There are two issues with your code. You refer to index 3 which is out of bounds because len(mrb) == 3. Secondly, you pass arrays to jaccard_dist which do not have type code 'L', as in the docstring example.

It is of course possible to check for these things, but the idea was to minimize overhead.

**Comment by daveuu** [comment]
Fair enough. Do you think the 'Q' arrays will ever give a wrong result even if they don't cause a crash? I appreciate the design choice for not checking types in the interests of speed though, so I suppose it doesn't matter what the output is: it's up to the user to check their input.

**Comment by andreasvc** [comment]
L and Q happen to be the same size on Intel 64-bit, so the results will always be identical. L and Q probably differ when you run on 32-bit or another platform. Checking the type of the arrays wouldn't be a problem, it happens only once per call (as opposed to checking whether indices are out of bounds). In any case the docstring is now more explicit.
