### ISSUE TITLE
Feature request: multi-threaded MultiRoaringBitmap e.g., jaccard_dist()

### ISSUE THREAD

**Issue by daveuu** [andreasvc/roaringbitmap#11]
In the case when many set comparisons are to be carried out, processing the contents of one MultiRoaringBitmap with several CPU cores would be more memory efficient than creating several MultiRoaringBitmaps with some common content to process each with one core. I know the GIL is freed in current implementation maybe invoking parallelism is possible from within Python? Alternatively, it seems Cython might have convenient facilities for parallel loops:
http://docs.cython.org/src/userguide/parallelism.html
I'll have a fiddle although it would be new coding territory for me.

**Comment by andreasvc** [comment]
Yes I think OpenMP is suited for this. I have used it before: https://github.com/andreasvc/subsequences/blob/master/parallelsubstr.pyx
Although looking at that now I find it dubious that it has "with gil" inside a prange...

If you do the threading from within Python, there's no need to change anything about MultiRoaringBitmap. You would simply divide up the indices arrays into as much subarrays as you have cores, and then start Python threads for each (using the threading module or concurrent.futures). The OpenMP approach would be superior because it avoids all Python overhead.

**Comment by daveuu** [comment]
So far I can get parallelisation of MultiRoaringBitmap.jaccard_dist() via Python code but only by multiprocessing, not multithreading. It seems to me the `nogil` parts of jaccard_dist() are not properly releasing the GIL thus preventing multiple threading? It could also be a bug in my code (uses ipython's `%timeit` and `%%timeit`):
```
from roaringbitmap import MultiRoaringBitmap
from roaringbitmap import RoaringBitmap
from random import sample
from array import array
# generate some bitmaps
num_bms = 2000
for_multi = []
for i in range(num_bms):
    for_multi += [RoaringBitmap(sample(range(99999),200))]

mrb = MultiRoaringBitmap(for_multi)

# generate some indices for pairwise comparisons
As = array('L')
Bs = array('L')
As_list = []
Bs_list = []
for n,a in enumerate(list(range(num_bms))[:-1]):
    for b in list(range(num_bms))[n+1:]:
        As.append(a)
        Bs.append(b)

# use an ipython magic command to time the calculation
%timeit mrb.jaccard_dist(As,Bs)
# ~3.26 s for 2000 . . .

# compare with using multiple processes and threads
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures import ThreadPoolExecutor
from itertools import chain as chain

nprocs = 3
# calculate a manual chunk size to prepare separate indices arrays to each jaccard_dict() call
chunk_size = int((len(As)+nprocs)/nprocs)
As_list = [As[p*chunk_size:(p+1)*chunk_size] for p in range(nprocs)]
Bs_list = [Bs[p*chunk_size:(p+1)*chunk_size] for p in range(nprocs)]

%%timeit
with ProcessPoolExecutor(max_workers=nprocs) as executor:
    res = list(executor.map(mrb.jaccard_dist, As_list, Bs_list, chunksize=1))
    res = list(chain(*res))

# 1.23 s on 3 processes

%%timeit
with ThreadPoolExecutor(max_workers=nprocs) as executor:
    res = list(executor.map(mrb.jaccard_dist, As_list, Bs_list, chunksize=1))
    res = list(chain(*res))

# 3.34 s on 3 threads but only one core used
```

**Comment by andreasvc** [comment]
The GIL was not actually being released, that requires a "with nogil:" block; try again with the latest commit.

**Comment by daveuu** [comment]
That's working now. A direct call takes 3.1 seconds. Perfect speed ups:
```
round(3.1/2, 2) == 1.55   # parallel x 2
round(3.1/3, 2) == 1.03   # parallel x 3
round(3.1/4, 2) == 0.78   # parallel x 4
```
Multiprocessing:
1.66 s on 2 processes
1.14 s on 3 processes
0.89 s on 4 processes

Multithreading:
1.62 s on 2 threads
1.09 s on 3 threads
0.83 s on 4 threads

And multithreading has the expected memory usage advantage: none extra used while multiprocessing scales linearly. This time overhead is good for my needs right now. Thanks for the quick update!
