### ISSUE TITLE
Strange .clamp() behaviour with some ranges

### ISSUE THREAD

**Issue by David-R-Walker** [andreasvc/roaringbitmap#12]
The `RoaringBitmap.clamp()` method seems to be broken for certain ranges:

e.g.

**Setup:**
    >>> from roaringbitmap import RoaringBitmap
    >>> b = RoaringBitmap([1,2,3])

**These work as expected:**
    >>> b.clamp(0, 4)
    RoaringBitmap({1, 2, 3})
    >>> b.clamp(0, 65535)
    RoaringBitmap({1, 2, 3})

**These ranges are not behaving consistently with the above:**
    >>> b.clamp(0, 65536)
    RoaringBitmap({})
    >>> b.clamp(0, 65537)
    RoaringBitmap({})
    >>> b.clamp(0, 65538)
    RoaringBitmap({1})
    >>> b.clamp(0, 65539)
    RoaringBitmap({1, 2})

**And now we seem to 'wrap around' to expected ranges again:**
    >>> b.clamp(0, 65540)
    RoaringBitmap({1, 2, 3})

If I understand the documentation correctly, *all* of the above should return a `RoaringBitmap({1,2,3})`.

**Comment by andreasvc** [comment]
Thanks for the report. Have to figure out what's going on here. For the time being, ``b & RoaringBitmap(range(0, 65536))`` does the right thing.
