### ISSUE TITLE
Intersection of 2 large sets causing aborts

### ISSUE THREAD

**Issue by ryazwinski** [andreasvc/roaringbitmap#13]
```
from pickle import load

print("set1")
with open('rset', 'rb') as ifile:
    rset=load(ifile)

print("set2")
with open('orset', 'rb') as ifile:
    orset=load(ifile)

print("intersection")
rset.intersection_update(orset)
print("complete")
```

aborts in the intersection:
```
Python(75946,0x7fff7704b000) malloc: *** mach_vm_map(size=18446744073709436928) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

test files at https://www.dropbox.com/s/yvahy3ynkdzvgl3/roaringbitmap_bug.tgz?dl=0

reproduces on OSX and Ubuntu 14.04 both in python3

**Comment by ryazwinski** [comment]
this still happens with a build from github repo (today).. I don't think it's fixed

**Comment by andreasvc** [comment]
Thanks for the bug report. Unfortunately the unit tests did not catch this one. The latest commit fixes the issue for me.

**Comment by ryazwinski** [comment]
Hrm.. just did a pull, uninstall and setup.py install.. still no joy here. (Currently on OSX, python 3.5.2)

**Comment by ryazwinski** [comment]
disregard that - had to force clean the cython artifacts... looks good now!  thanks

**Comment by andreasvc** [comment]
Good. I use ``make`` which saves typing and does that automatically...
