### ISSUE TITLE
pickle/unpickle bug

### ISSUE THREAD

**Issue by ryazwinski** [andreasvc/roaringbitmap#14]
Found a bug when pickling/unpickling a dict with RoaringBitmap elements.  Doesn't happen all the time, but does in the case attached.

dd.out - the dict that was pickled
*.pickle the pickled data
bug.out - ipython3 session showing the bug

[bug.zip](https://github.com/andreasvc/roaringbitmap/files/506264/bug.zip)

**Comment by andreasvc** [comment]
Thanks for the report! Empty sets caused the return value of a memory allocation to be interpreted as failure. Fixed in latest commit.

**Comment by andreasvc** [comment]
BTW pickling a dictionary of roaring bitmaps is exactly the use case that is optimized by MultiRoaringBitmap. It avoids the overhead of copying and deserializing data to memory.
