### ISSUE TITLE
Strange behavior using git version of roaring bitmap

### ISSUE THREAD

**Issue by edmcman** [andreasvc/roaringbitmap#19]
Basically, this code triggers the if branch for some values of `set1` and `set2`:

```seen = RoaringBitmap()
seen|=set1
seen|=set2

if len(seen - set1 - set2) != 0:
    print "What?", len(seen - set1 - set2)
```

Full example available [here](https://gist.github.com/edmcman/395e3cc936f846567d5dfd0cb43122a2).  I actually ran this through a testcase minimizer and it was obviously unable to do much, which suggests this is a difficult to trigger bug.

**Comment by edmcman** [comment]
The same testcase does not trigger roaringbitmap 0.5 on pip.

**Comment by edmcman** [comment]
Using gitbisect suggests that fa8432eb1b5691d9bec6ff70716b97645e53faf2 is to blame

**Comment by andreasvc** [comment]
Simpler testcase: ``set1=range(4095); set2=range(2)``. Seems a bitmap result is not correctly converted to an array after the union, haven't figured out why.

**Comment by andreasvc** [comment]
Thx for the report!
