### ISSUE TITLE
Usage as a library?

### ISSUE THREAD

**Issue by pombredanne** [andreasvc/roaringbitmap#2]
@andreasvc could you consider may be using the LGPL instead of the GPL? this is a library after all and makes it hard to reuse in Apache-licensed code...
Thank you for your kind consideration

**Comment by pombredanne** [comment]
FWIW, the upstream implementation is now Apache-licensed. https://github.com/lemire/RoaringBitmap/blob/master/LICENSE

**Comment by andreasvc** [comment]
I have now clarified that the license is GPLv2 or later, so it is now compatible with Apache v2 license.
I may consider LGPL in the future if there's a particular reason but for now I prefer GPL.

**Comment by pombredanne** [comment]
Fair enough. I was considering using it in some Apache-licensed code of mine there https://github.com/nexB/scancode-toolkit so I will pass for now. Thank you for your quick reply back then that I should have acknowledged!

**Comment by lemire** [comment]
@pombredanne 


Whoosh is Python and BSD and includes a roaring implementation.

https://pypi.python.org/pypi/Whoosh/

**Comment by pombredanne** [comment]
@lemire Thanks ++! indeed! https://github.com/mchaput/whoosh/blob/0d05bc3d6213bd6b4b2452cdcbbbe630fbd7191a/src/whoosh/idsets.py#L610 ...

**Comment by pombredanne** [comment]
@lemire I shall say that this is really a wonderful structure of yours! :+1:
