### ISSUE TITLE
MultiRoaringBitmap slicing return type

### ISSUE THREAD

**Issue by remiadon** [andreasvc/roaringbitmap#29]
currently a it's possible to slice a ``MultiRoaringBitmap``, but it returns a list of ``ImmutableRoaringBitmap``, see [this line](https://github.com/andreasvc/roaringbitmap/blob/master/src/multirb.pxi#L168) 

```python
>>> from roaringbitmap import MultiRoaringBitmap
>>> mrb = MultiRoaringBitmap([range(i) for i in range(2, 10)])
>>> mrb[:3]
[ImmutableRoaringBitmap({0, 1}),
 ImmutableRoaringBitmap({0, 1, 2}),
 ImmutableRoaringBitmap({0, 1, 2, 3})]
```

It's actually possible to get a new MultiRoaringBitmap, by calling the constructor
```python
>>> MultiRoaringBitmap(mrb[0:5])
<roaringbitmap.MultiRoaringBitmap at 0x7fa0736859a8>
```
but I think this makes a copy of the Bitmaps in question

Would that make sense if ``MultiRoaringBitmap.__getitem__`` returned an instance of ``MultiRoaringBitmap`` ?

**Comment by andreasvc** [comment]
A MultiRoaringBitmap manages and owns the storage in memory or on disk of the bitmaps it contains, so returning a MultiRoaringBitmap requires copying the data. If you do want a new instance of MultiRoaringBitmap with copies, you can do `MultiRoaringBitmap(mrb[0:5])` as in your example.

Do you have a use case where having slices without making copies is crucial? It is probably possible to create a version of MultiRoaringBitmap that references a slice of another one, but I'm not sure implementing that is worth the effort ...

**Comment by remiadon** [comment]
My use case is the following

I am using Bitmaps to represent a transactional database : for every item in my database, I keep track of transaction ids where this item occurred. 
```python
>> from collections import defaultdict
>> from roaringbitmap import RoaringBitmap
>> database = [['milk', 'chocolate', 'banana'], ['banana', 'nuts', 'milk'], ['orange juice', 'milk', 'chocolate']]
>> d = defaultdict(RoaringBitmap)
>> for idx, transaction in enumerate(database):
>>    for item in transaction:
>>       d[item].add(idx)

>> d
defaultdict(roaringbitmap.RoaringBitmap,
            {'milk': RoaringBitmap({0, 1, 2}),
             'chocolate': RoaringBitmap({0, 2}),
             'banana': RoaringBitmap({0, 1}),
             'nuts': RoaringBitmap({1}),
             'orange juice': RoaringBitmap({2})})

```

Let's imagine I want to know how many times 'milk' and 'chocolate' occurred together : 
```python
from functools import reduce
>> keys = ['milk', 'chocolate'] 
>> len(reduce(RoaringBitmap.intersection, (d[k] for k in keys)))
2
```

As my database definition is static (I ingest data only once and do not modify my data representation), I was hopping to get better performance using `MultiRoaringBitmap`, computing intersections on subsets of it

**Comment by andreasvc** [comment]
It sounds like you should map your keys to integers and use https://roaringbitmap.readthedocs.io/en/latest/#roaringbitmap.MultiRoaringBitmap.intersection

**Comment by remiadon** [comment]
Right on point,
thanks for the support

Closing this
