### ISSUE TITLE
len(bitmap) != bitmap.numelem()

### ISSUE THREAD

**Issue by hmijail** [andreasvc/roaringbitmap#30]
```
>>> r=RoaringBitmap([0])
>>> len(r)
1
>>> r.numelem()
2
```

**Comment by andreasvc** [comment]
This is working as intended. len() gives cardinality, numelem() gives the amount of storage used. This is documented, but if you have suggestions about improving the documentation, feel free to make a pull request.

Note that numelem() counts 1 uint16_t for the high bits of the elements in a block, and adds the number of uint16_t integers for the low bits of the elements in a block.
