### ISSUE TITLE
`MultiRoaringBitmap.jaccard_dist` against a query coming from an external `RoaringBitmap`

### ISSUE THREAD

**Issue by ljmartin** [andreasvc/roaringbitmap#32]
Hi rbm, 
Is it possible to calculate bulk Jaccard distances across a `MultiRoaringBitmap` where the query is not already within the `MultiRoaringBitmap`?

A straightforward way might be:
```python
multi_rb = MultiRoaringBitmap(list_of_indices, filename='index')
rbm = RoaringBitmap([0,3,6])
jacs = [r.jaccard_dist(b) for b in multi_rb]
```
Perhaps there's not much overhead working directly in python, but I figured there might be a cleverer/faster way to do this. 
Thanks!
Lewis

**Comment by andreasvc** [comment]
I added a method for this:
```
multi_rb.jaccar_dist_single(rbm)
```

**Comment by ljmartin** [comment]
cool, thanks a lot!
