### ISSUE TITLE
Nonempty RoaringBitmap throws ValueError on pop()

### ISSUE THREAD

**Issue by rqx** [andreasvc/roaringbitmap#9]
Following code throws `ValueError`:

    bits = RoaringBitmap([60748, 28806, 54664, 28597, 58922, 75684, 56364, 67421, 52608, 
                          55686, 10427, 48506, 64363, 14506, 73077, 59035, 70246, 19875, 
                          73145, 40225, 58664, 6597, 65554, 73102, 26636, 74227, 59566, 
                          19023])
    while bits:
        bits.pop()

**Comment by andreasvc** [comment]
Thanks for reporting!
